services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: 'mysql'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_DB: 'devops'
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: 'mysql'
    image: 'mysql:5.7'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'devops'
    volumes:
      - mysqldb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysqldb:
